
"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './page.js'
import './index.css'
import { GoogleOAuthProvider } from "@react-oauth/google"

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <GoogleOAuthProvider clientId='1009282809407-sh8h2kgmot2q295a503sl5530pldnaj9.apps.googleusercontent.com'>

    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </GoogleOAuthProvider>
  );
}